name: Semantic Release (Standalone)

# This workflow is for manual semantic release triggers only
# The main semantic release flow is integrated into databricks-cicd.yml

on:
  workflow_dispatch:

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    outputs:
      new-release-published: ${{ steps.semantic.outputs.new-release-published }}
      new-release-version: ${{ steps.semantic.outputs.new-release-version }}
      new-release-git-tag: ${{ steps.semantic.outputs.new-release-git-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install semantic-release dependencies
        run: |
          npm install --save-dev semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

      - name: Semantic Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release

      - name: Output Release Info
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          echo "New release published!"
          echo "Version: ${{ steps.semantic.outputs.new-release-version }}"
          echo "Git Tag: ${{ steps.semantic.outputs.new-release-git-tag }}"